basePath: /v1
info:
  contact: {}
  description: fxPixel LED lighting effects REST service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: fxPixel
  version: "1.0"
paths: {}
swagger: "2.0"
